server:
  port: 10001

spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  application:
    name: asset
  ai:
    mcp:
      server:
        name: asset
        version: 1.0.0
        type: ASYNC
        sse-message-endpoint: /mcp/message
        enabled: true


logging:
  level:
    org.springframework.ai: debug

